### ISSUE TITLE
Can't install!

### ISSUE THREAD

**Issue by tomkail** [RageAgainstThePixel/com.utilities.rest#1]
# Bug Report
Seeing this error when installing via Github URL:
```
[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/RageAgainstThePixel/com.utilities.rest.git#upm]:
  Package com.utilities.rest@https://github.com/RageAgainstThePixel/com.utilities.rest.git#upm has invalid dependencies or related test packages:
    com.utilities.async (dependency): Package [com.utilities.async@1.2.0] cannot be found [NotFound].
```

**Comment by StephenHodgson** [comment]
You also need to manually install the [`com.utilities.async`](https://github.com/RageAgainstThePixel/com.utilities.async) dependency.

If you're unfamiliar with how to install the dependencies for git packages I encourage you to install via the preferred [openupm method instead](https://github.com/RageAgainstThePixel/com.utilities.rest#via-unity-package-manager-and-openupm) because it supports dependencies and versioning better.
