### ISSUE TITLE
Please update the examples on the root ReadMe with latest implementations and examples

### ISSUE THREAD

**Issue by SimonDarksideJ** [RageAgainstThePixel/com.utilities.rest#73]
With all the recent changes, the main ReadMe has not been kept up to date, as such, none of the examples provided are functional and require additional parameters.

**Comment by StephenHodgson** [comment]
Nothing has really changed much since your large refactor in #65/#66.
If you'd like to open a PR to update the docs with the refactor changes you made there, you are more than welcome.

I've only updated logging string outputs and fixes a few concurrency bugs.
I did update `Rest.DownloadAudioClipAsync` but only added optional stream and compression parameters.

**Comment by SimonDarksideJ** [comment]
Essentially, although a single "RestParameters" example has been added, the other examples do not make it clear it is optional or required, additionally, some requests like `AssetBundles` are malformed.

But I will do a PR to correct this.
